general:
  checkForUpdates: true
  verbose: false
  locale: en_US
type:
  big:
    uniqueName: 'big'
    displayName: '&7Big &eBackpack'
    inventoryRows: 6
    customModelData: 3
    texture: 'ewogICJ0aW1lc3RhbXAiIDogMTYzMzg2MjQwNTg4NSwKICAicHJvZmlsZUlkIiA6ICI1NjY3NWIyMjMyZjA0ZWUwODkxNzllOWM5MjA2Y2ZlOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJUaGVJbmRyYSIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9kYTMzMTY5YjcyY2Y4OTE4YjgyYzViZDI3Y2JhOWVlNmMwZWI4OTE2NDA0MDQ4MGJiMjdmODUzNGUwZmE1ODA3IiwKICAgICAgIm1ldGFkYXRhIiA6IHsKICAgICAgICAibW9kZWwiIDogInNsaW0iCiAgICAgIH0KICAgIH0KICB9Cn0='
    lore:
      - '&aA Big Backpack'
    recipe:
      discover: true
      group: 'null'
      patternOne: 'LCL'
      patternTwo: 'ECE'
      patternThree: 'DCD'
      patternMapping:
        L: LEATHER
        E: LEAD
        C: CHEST
        D: DIAMOND
  medium:
    uniqueName: 'medium'
    displayName: '&7Medium &eBackpack'
    inventoryRows: 3
    customModelData: 2
    texture: 'ewogICJ0aW1lc3RhbXAiIDogMTY3NDM0NDQ0MzY4NywKICAicHJvZmlsZUlkIiA6ICIxMzdmMjg3MjUwOTE0ZmI4YjA0ZTYwYjg4MWUwZWE2YiIsCiAgInByb2ZpbGVOYW1lIiA6ICJub3JtYWxpc2luZyIsCiAgInNpZ25hdHVyZVJlcXVpcmVkIiA6IHRydWUsCiAgInRleHR1cmVzIiA6IHsKICAgICJTS0lOIiA6IHsKICAgICAgInVybCIgOiAiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lZjhlZDY4NWIzYzNjYWI4NDM1ZDBmNmIwZDJkZGI0NmRmYTNhYzk2ZmUyZjlhNmQ3NDhmNzExOTFjMGI1MjJiIgogICAgfQogIH0KfQ=='
    lore:
      - '&aA Medium Backpack'
    recipe:
      discover: true
      group: 'null'
      patternOne: 'LSL'
      patternTwo: 'ECE'
      patternThree: 'ICI'
      patternMapping:
        L: LEATHER
        S: STICK
        E: LEAD
        C: CHEST
        I: IRON_INGOT
  small:
    uniqueName: 'small'
    displayName: '&7Small &eBackpack'
    inventoryRows: 1
    customModelData: 1
    texture: 'ewogICJ0aW1lc3RhbXAiIDogMTYxMzM4Nzk2NDUxNSwKICAicHJvZmlsZUlkIiA6ICJkZTU3MWExMDJjYjg0ODgwOGZlN2M5ZjQ0OTZlY2RhZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJNSEZfTWluZXNraW4iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGFlMTg3MTQ1ZWU3MzJlN2MwMDkwNWE5YzE2ZWQxZTQzYmE4OGQ1NjI0YTZmNGFmODI5ZjEwNDUzZmNjOTE2NSIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9'
    lore:
      - '&aA Small Backpack'
    recipe:
      discover: true
      group: 'null'
      patternOne: 'LSL'
      patternTwo: 'ECE'
      patternThree: 'LLL'
      patternMapping:
        L: LEATHER
        S: STICK
        E: LEAD
        C: CHEST